catch invalid local folder

diff --git a/ssync b/ssync
--- a/ssync
+++ b/ssync
@@ -8,21 +8,21 @@ remoteroot=$2
 shift 2
 remotes="$@"
 
-[ -z "$syncroot" ] && syncroot="."
-
-if [ "$syncroot" == "." ]
+if [ ! -e "$syncroot" ]
 then
-    syncroot=`pwd`
+    echo "error: local file ¬∃"
+    echo "exiting"
+    exit 1
 fi
 
-modified=`stat -c %Y ${syncroot}`
+modified=`stat -c %Y $syncroot`
 
 function init() {
     echo "copying ssh public key to remote"
     for remote in $remotes
     do
         ssh-copy-id $remote
-        [ $? -ne 0 ] echo "failed copying ssh key to $remote"
+        [ $? -ne 0 ] && echo "failed copying ssh key to $remote"
     done
     echo "finished init process"
 }
@@ -31,9 +31,9 @@ function copyfolder() {
     echo "begin sync cycle"
     for remote in $remotes
     do
-        echo "syncing to $remote:${remoteroot}"
-        scp $syncroot "${remote}:${remoteroot}"
-        [ $? -ne 0 ] && echo "failed sycning to syncing to $remote:${remoteroot}"
+        echo "syncing to $remote:$remoteroot"
+        scp $syncroot "$remote:$remoteroot"
+        [ $? -ne 0 ] && echo "failed sycning to syncing to $remote:$remoteroot"
     done
 
     echo "finished syncing"    
